spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
      - id: auth-service
        uri: http://localhost:3000
        predicates:
          - Path=/auth-service/**

      - id: task-service
        uri: lb://TASK-SERVICE
        predicates:
          - Path=/task-service/**

      - id: notification-service
        uri: lb://NOTIFICATION-SERVICE
        predicates:
          - Path=/notification-service/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/