spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes: auth-service
      uri: http://localhost:3000
      predicates:
        - Path=/auth-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/