spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/